# Generated by Django 3.0.3 on 2020-09-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfautomation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poidescription',
            name='poi_2',
            field=models.CharField(max_length=300, null=True, verbose_name='POI 2'),
        ),
        migrations.AlterField(
            model_name='poidescription',
            name='poi_3',
            field=models.CharField(max_length=300, null=True, verbose_name='POI 3'),
        ),
        migrations.AlterField(
            model_name='poidescription',
            name='poi_4',
            field=models.CharField(max_length=300, null=True, verbose_name='POI 4'),
        ),
        migrations.AlterField(
            model_name='poidescription',
            name='poi_5',
            field=models.CharField(max_length=300, null=True, verbose_name='POI 5'),
        ),
    ]
