# Generated by Django 3.0.3 on 2020-09-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0004_auto_20200820_1502'),
        ('wfautomation', '0002_auto_20200907_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSurveyDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_1_description', models.CharField(blank=True, max_length=300, null=True)),
                ('poi_1_measurement', models.FloatField(blank=True, default=0, null=True)),
                ('poi_1_document', models.FileField(upload_to='user_directory_path')),
                ('poi_2_description', models.CharField(blank=True, max_length=300, null=True)),
                ('poi_2_measurement', models.FloatField(blank=True, default=0, null=True)),
                ('poi_2_document', models.FileField(upload_to='user_directory_path')),
                ('poi_3_description', models.CharField(blank=True, max_length=300, null=True)),
                ('poi_3_measurement', models.FloatField(blank=True, default=0, null=True)),
                ('poi_3_document', models.FileField(upload_to='user_directory_path')),
                ('poi_4_description', models.CharField(blank=True, max_length=300, null=True)),
                ('poi_4_measurement', models.FloatField(blank=True, default=0, null=True)),
                ('poi_4_document', models.FileField(upload_to='user_directory_path')),
                ('poi_5_description', models.CharField(blank=True, max_length=300, null=True)),
                ('poi_5_measurement', models.FloatField(blank=True, default=0, null=True)),
                ('poi_5_document', models.FileField(upload_to='user_directory_path')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.Site')),
            ],
        ),
    ]
