# Generated by Django 3.0.3 on 2020-09-07 06:41

from django.db import migrations, models
import wfautomation.models


class Migration(migrations.Migration):

    dependencies = [
        ('wfautomation', '0003_sitesurveydocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesurveydocuments',
            name='poi_1_document',
            field=models.FileField(upload_to=wfautomation.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='sitesurveydocuments',
            name='poi_2_document',
            field=models.FileField(upload_to=wfautomation.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='sitesurveydocuments',
            name='poi_3_document',
            field=models.FileField(upload_to=wfautomation.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='sitesurveydocuments',
            name='poi_4_document',
            field=models.FileField(upload_to=wfautomation.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='sitesurveydocuments',
            name='poi_5_document',
            field=models.FileField(upload_to=wfautomation.models.user_directory_path),
        ),
    ]
