# Generated by Django 3.0.3 on 2020-05-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=16, unique=True, verbose_name='Site ID')),
                ('site_name', models.CharField(max_length=64, unique=True, verbose_name='Site Name')),
                ('site_lat', models.FloatField(verbose_name='Latitude')),
                ('site_long', models.FloatField(verbose_name='Longitude')),
                ('site_cluster', models.CharField(max_length=64, verbose_name='Cluster')),
                ('site_state', models.CharField(max_length=32, verbose_name='State')),
                ('site_pole_owner', models.CharField(max_length=64, verbose_name='Pole Owner')),
                ('site_pole_id', models.CharField(max_length=64, verbose_name='Pole ID')),
                ('site_rfnsa_id', models.CharField(max_length=12, null=True, unique=True, verbose_name='RFNSA ID')),
                ('site_acma_id', models.CharField(max_length=12, null=True, unique=True, verbose_name='ACMA ID')),
            ],
            options={
                'verbose_name': 'SiteBasicData',
                'verbose_name_plural': 'SiteBasicData',
                'db_table': 'site_basic',
                'ordering': ['site_id'],
            },
        ),
    ]
