# Generated by Django 3.0.3 on 2020-05-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_site_id', models.CharField(max_length=16, verbose_name='log_site_id')),
                ('log_created', models.DateTimeField(editable=False)),
                ('log_modified', models.DateTimeField()),
                ('log_info', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'site_log_info',
                'ordering': ['-log_created'],
            },
        ),
    ]
