# Generated by Django 3.0.3 on 2020-06-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0002_siteloginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteloginfo',
            name='log_user',
            field=models.CharField(default='None', max_length=64, verbose_name='log_user'),
        ),
    ]
