# Generated by Django 3.0.3 on 2020-10-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0004_auto_20200820_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_acma_id',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='ACMA ID'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_pole_id',
            field=models.CharField(max_length=64, null=True, verbose_name='Pole ID'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_pole_owner',
            field=models.CharField(max_length=64, null=True, verbose_name='Pole Owner'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_rfnsa_id',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='RFNSA ID'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_vha_id',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='VHA Site ID'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_vha_name',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='VHA Site Name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(max_length=16, unique=True, verbose_name='TPG Site ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='TPG Site Name'),
        ),
        migrations.CreateModel(
            name='SiteSwap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_plan', models.BooleanField(default=False, verbose_name='Swap Plan')),
                ('swap_schedule', models.CharField(max_length=32, verbose_name='Swap Schedule')),
                ('swap_status', models.CharField(max_length=32, verbose_name='Swap Status')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_swap', to='sitedb.Site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_plan', models.BooleanField(default=False, verbose_name='Activation Plan')),
                ('activation_schedule', models.CharField(max_length=32, verbose_name='Activation Schedule')),
                ('activation_status', models.CharField(max_length=32, verbose_name='Activation Status')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_activation', to='sitedb.Site')),
            ],
        ),
    ]
