# Generated by Django 3.0.3 on 2020-10-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0005_auto_20201027_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteactivation',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_activation', to='sitedb.Site'),
        ),
        migrations.AlterField(
            model_name='siteswap',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_swap', to='sitedb.Site'),
        ),
    ]
