# Generated by Django 3.0.3 on 2020-11-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0007_auto_20201106_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteloginfo',
            name='log_datetime_info',
            field=models.DateTimeField(null=True),
        ),
    ]
