# Generated by Django 3.0.3 on 2020-08-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_usersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_eme',
            new_name='is_tpg_eme',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_tpg_pm',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_rf',
            new_name='is_tpg_rf',
        ),
        migrations.AddField(
            model_name='user',
            name='is_tpg_saed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vha_rf',
            field=models.BooleanField(default=False),
        ),
    ]
